### ISSUE TITLE
No support for "dnom" and "numr"

### ISSUE THREAD

**Issue by quitequinn** [kennethormandy/utility-opentype#5]
I think it would make sense to add these in..

**Comment by quitequinn** [comment]
Adding these breaks the test...

```bash
 1) should not break perf budget
```

I'm not well versed in testing... and would love to chat about it and your approach to compiling sometime

**Comment by kennethormandy** [comment]
Thanks so much for the PR!

So basically the performance budget is so I don’t go overboard with adding every OpenType feature class to this module—or, at least, it’s not in the core. In this case, the test just checks if the module is within 1.75kb gzipped so that I ensure I am writing concise CSS.

Could of concerns with this, it looks like that the `.sinf` class just got copied in a couple of times? I assume that was just a copy paste error.

Also, the `.sinf` class might not be the best one to base `.dnom` and `.numr` on, since the main stuff is actually coming from this. I added comments:

```css
.subs,
.sinf {
   /* If it doesn’t support `font-variant` */
  @supports not (font-variant-position: sub) {
    font-feature-settings: "subs"; /* …use `font-feature-settings` */
    @supports (font-feature-settings: "subs") { /* If it does support that…*/
      font-size: 1em; /* Override the browser defaults for `<sub>` and `<sup>` */
      vertical-align: baseline;
    }
    /* Since Safari lies and says it supports `font-feature-settings`, fix fallback subscript */
    @supports (overflow: -webkit-marquee) and (justify-content: inherit) {
      vertical-align: sub; /* Restore the browser default for `<sub>` and `<sup>` */
      font-size: smaller;
    }
  }
  /* Hopefully none of that is applicable, and we just use `font-variant` */
  font-size: inherit;
  font-variant-position: sub;
}
```

Does that kind of make sense? I might need to write up a contributing guide that explains that more in depth.

**Comment by quitequinn** [comment]
Oops thanks for that.. missed the sinfs.. 
I'll make a revision... I hope it helps.

**Comment by quitequinn** [comment]
I couldn't find a font-variant for dnom or numr... so i think the new revision is the only solution.

**Comment by quitequinn** [comment]
I'm not setting
```css
font-size: 1em; /* Override the browser defaults for `<sub>` and `<sup>`  ...etc*/
```
because the class doesn't have to be used with tags

**Comment by kennethormandy** [comment]
Okay, thanks. If you delete the `.sinf` duplicates and push it to this branch, I will take a look at merging the other stuff.

Can you elabourate or open a separate issue for the `1em` thing? Thanks!

**Comment by quitequinn** [comment]
right!.. working on an example and confirming faked dnom and numr.

in the case of 1em for subs and sinf:
If the intention is to override <sub> and <sup> then I would prefer the 1em targeting only those tags. In this case the 1em is conflicting my div that has .sinf and forcing it to be smaller than the rest. (ex. because the less specific definition is to set it at 2em)

**Comment by quitequinn** [comment]
Another thing that might be worth considering is finding a solution for removing lineheight changes for the false fallbacks.

In the meantime `linehight: 0;` works

![screen shot 2016-02-24 at 1 17 59 pm](https://cloud.githubusercontent.com/assets/2885870/13301317/358522b2-daf9-11e5-81cd-1407751c424e.jpg)
![screen shot 2016-02-24 at 1 18 17 pm](https://cloud.githubusercontent.com/assets/2885870/13301318/35866d16-daf9-11e5-8163-d5ad21539d14.jpg)

**Comment by quitequinn** [comment]
I think I've set the fake heights appropriately.. but its difficult to say I have a agreed upon solution for the .numr—since I can't find a good definition online.

Type design aside—the numr is dependent on the placement of the dnom.. and the highest we can set it is v-align super... so unless we want to adding in top or some other sort of placement thats the best we can do.

![screen shot 2016-02-24 at 1 29 09 pm](https://cloud.githubusercontent.com/assets/2885870/13301691/07d2aebe-dafb-11e5-814f-0117554964d5.jpg)

https://jsfiddle.net/w9jtrvtn/1/

**Comment by kennethormandy** [comment]
Hey thanks for taking time to revise that. I iterated on that and I think this should work, which should be the same result as what you had, but should compile a bit smaller:

```css
.sinf,
.dnom,
.numr {
  @supports (font-feature-settings: "sinf"), (font-feature-settings: "dnom"), (font-feature-settings: "numr") {
    font-variant-position: normal;
    vertical-align: baseline;
  }
  /* Since Safari lies and says it supports `font-feature-settings`, fix fallback subscript */
  @supports (overflow: -webkit-marquee) and (justify-content: inherit) {
    vertical-align: sub;
    font-size: smaller;
  }
}

.sinf {
  font-feature-settings: "sinf";
}

.dnom {
  font-feature-settings: "dnom" 1;
}

.numr {
  font-feature-settings: "numr" 1;
}
```

…unfortunately, that is causing me problems with Sass now, because they still have a bug parsing comma-separated queries or something. I will have to take a look at that.

That said, I took a closer look at the OpenType spec and it has this part:

> _UI suggestion:_ This feature should normally be called by an application when the user applies the frac feature.

[Source](https://www.microsoft.com/typography/otspec/features_ko.htm#numr) (I’m sure you checked that too, just trying to understand it better.)

In this library, the CSS classes are the UI / API. So I’m wondering if `.frac` is sufficient? I’m thinking that’s probably why there isn’t a `font-variant-*` property for `numr` or `dnom`. Do you have a usecase where `.frac` won’t work?
